title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
title: J. Skowronski
description: PhD. Student in Nuclear Astrophysics at the Universit√† degli Studi di Padova